apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAIUjBb1QbOqV5/QyUqaDA0A3A05IJuT0Jk1Y96u6ZXhcbj4UMeJ4ba8sSzdKpSj3nz8fBBEKmwwcl8YJTMc4mrxyPH68ApIzbxFonkU+3UPAt2cs7eyS6EHVf0BSRsFexf64SdCPYu/TT09L+Wg5bjWvYqikdr6/pxdarYaP3hIugLppKlS7PNvKn1pFjY00te1gChTUbJv7iQNKIK70sKaUVCLxXiCsWL69uZO08FsN0jXQ1cbsZiovZUfG7udfyFPbGe+XcdjudU5jRadtnFOI+pTZPD7nOV2u9pBldu8PXWQ9rAKykmM3IKDeSVrmHjxxrgPj0JckIeaYiZp6vnoNOTFQt57jndz511qHWtelLOVVDe+hzoAvpXFrkFnbFi92vbMotCOfNzRn85r2FJj0Ry/d4Y2D6aPjrRk9pGPQaV5JSsprqCuV8CW+QvRg5h3ZGKwV4Zv/bTi100RFfzlvqxexH+x+sMAfkYpoKfo+Suxqln7IAMn79GHTG8la0+g3lulL8G4qdpi0bHITES2Fde2sPsJE/+KgW1x7PmxGOFFLmb4AKMwKrozPIm5WkQHO401tX0DfaeYi4NqrQR4DpdIiT+TghuXOXqzLZd9xecOUYGvQ6Lhz3znVHzVnDstnDnBheEeslx/ynrgXMMWXoPfvnk2ZwCkai5GRmFOnPtQ//bNu0FVrJ5XU76w4gHrz2gMvusKqc7vzqg0CCsi2WmPD3rVvXLgnAIkIVh8ne+OoCYJpDN
    username: AgCZ+DscTgmzvqy48OlOc4rNHW3KmwjnwIh++TZpl4HJti9EN9Cw7NDaZigMQUzWMT/irHFNH1T6QkPbBe+kDtUmpeAxopB/qJurHFloiLvB4oTqIdj+v97E3ut/fPLLXjKopL9ANk6t6VETkojA49OfTe12KIYkSwOq5v1B9VgSLz9r0Imoz/IAWyppB4uXc1CoJDDZetwx/vkQXuY7ltC5zCelkKuhrXZRm9ICYWrsDfWhr7P8v4U0C/2bYqEVy6GTgraU2MgL6Q7Xzx1UFztLKoZMNuRh/LJ5HT+64JmxcLtyRz1Z4k9tcatxFZg29n3JseCPUReXO1DV2w8OibB1Ky8PFuu+ebh9wSKqiyvgNzTomnsKBmZ4pDMkoailN+cjnvoaLUwaTp8T0+J7RQnvnIQh+pKIv2J9VgiTxA5VvKFXR2AtBa28m5qYvkmfmBJksLwyv2w5ytI2P+4AEHZypYRxgTL4krgTcOoHU4B9iohfVENnBaq9izX5AW6KGBwiGonilGtNkRKpVrGqjAtD42AK6YcpCmWGCBIjgV+dwlD44GpEyK2Wza5RoBWDnvOBwUxcx95kP4kOuXPIq6aqX8Xf8a9dbLMzNmHYnNBLFMlYDNnfjwPCQQMaBZ9VBYD5gyjzAGivf63PCKUrr60bMJoKt7dK6mh3ERkmqFCQxmc6UBuZFwYX+hr4SaPtAhuMeqSD1rbNd50=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

