apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgClk/fG5/Ps0PsGUIAMIVIXFH4th7b5CcH4bH39kK15p7GtUW+g1od3xDrhFheoeO4YWoGxWtC7oeHIj8/IwmU7mDmeo0Fx6ie+fJ/6Q6Z5MtSIqs3Xf2EOpsMUCIv5AGt8MhlmvU3vmudHwufq5k02OpCGUO5+TQtTrzqwi3K2S0F9wE7HDL6qP3FD6vtIZFFRJAQ8JNidygXkSbne6yuWjlcw+EUqHz+sSldrcoPC2Cd77q7zXAxKO32S+8iiHdronaBhaw16+w3HIxL/W37/P6OQAk+j6Vme4e3MCNA7vBgESKzxO5QsGA8Tf7ZY5tbO525zKbDlquRifla/otn2MC61Rnc8CklKgle7vflmrDmGsyc1q8FgsYsd4L2pWnD97ks0fX5cOXvwet06gSPcHXDpD+f4e+8Jc5I4gf3lbcIaGbwy6TWy0KS9vtwiPVtAC0ebB7goGYhz/JXPUV0QlFEf5N867vLzRBA73eXmzhidrt+Is0zCCu5SxqwML/2TDY7NHl/t5P+7xAUf1b2cThZF1nyiADHs7a3l+ixwrZ3gTNa39rkQl3inkS3PG5AZJDpHdAUpujNs8PCLH7lmcEK3BIRypqdTVFcZSDTO7CoJbbyo4p90GJVId7A8KD7HPJYx3ID89uVbSNxq9CuhOAGeFu65tEZTmGULkuMHGGU/w75wrmzYbe6J4nliy5kFJ/jue0GAhCyxGfs4ZtBPBQ5GQFayvE0mBNbFn5BWIoJNILRwRxvYHzF6WPwlwSYeMGxSmGGqWjftBCc6sZbATLHR8LeNxNGgP1RsUx2Lm6oUD4NKCucWxKCIeNlhVWU8efqGGRMSbfthRR204rvWqMORtmqzByeCrFKiw5YvIHNpGo15W7tXM02pNq0vVjb3JrVcIRJWTpgq7NQbBQ4wUAobNNQ26vXLMb0cYGg2Tcm2QM0hi6H/xgdhR1lHygk=
    IBM_ENTITLED_REGISTRY_USER: AgBizGLbV9yXZxC+cvSb4dUpEBMxDsr5IkHolUdQrOMQQn/Rr1mj4NkWItuwzH9gC/5/BdeyHujjpTu5uiQKT7bqw+OPW15aICWCKtQZuuCxzVXphsxVAio74mHatQoEmr5Jw4Ab2Oq7c9/uImOSiYQ0yzW+2raw1fQq1j6Xe4H+xEVBWuxgxgccHO1qw1nau9VcGAAMtyBsbRnVaS3D+tBh5cNTMIVDxGu3Dfp/M5Kixq9hn7Yl/r+DhxkOLSDt9JHi/79/80l8fjPJDu+edSkIiciS+mwwwlajU5wLfq4wJgxLpqtOBijcUEFyoMMjkmN7W9B3+IAzlrsyZR8jKaz6biL3jDK6rerrqIWqyIoMkZG/9+AvaYbbH/udvLK4/wUMex6q+3njVwxAvoNXu0ufTM8y3wZxQSZTA4PdHZDKRpFvTOsgkphjRI9GQ09X9IzAeZkLvgzrAN2qDiQmh7jfRCRGUeVWW6QHnwevVXFxod33uvReTr031AJeqCZlkf3Be6SI6LyJzBoE+TWIzqu7unNsfK2Kp9AqiR1VM5dCllJXVGIRH9Is8Fn3EQyvLnjygJNYH4nzIR+cEm7bpk6iP7Q72o9DiwFfQS060iQ/TJstdG7XH+9UTeOlprpB/cty8gKj5xCLiJpMRhcNRT+BYAqgwu9qY86PrFKq5R47hVS+TTOF88zgVkyeI/EfFe2gKw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

